[package]
name = "lapce-deno"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.59"
serde = { version = "1.0", features = ["derive"] }
lapce-plugin = { git = "https://github.com/lapce/lapce-plugin-rust", branch = "master" }
